### ISSUE TITLE
release tags are missing

### ISSUE THREAD

**Issue by CvH** [kodi-game/game.libretro.uae4arm#2]
Not sure this is intended or not but there are no release tags and ofc no releases like at the other `game.libretro.*` addons.

**Comment by garbear** [comment]
tags are created by kodi-game-scripting, see https://github.com/kodi-game/kodi-game-scripting/blob/master/kodi_game_scripting/config.py#L103

uae4arm fails to build for desktop linux, which is where we load the .so and parse for settings and info. running kodi-game-scripting on an RPi would be a fun exercise, maybe I'll try this someday. the script doesn't take much effort if you'd like a help there.

**Comment by garbear** [comment]
I installed ubuntu server 20.04 arm64 on a raspberry pi 3. uae4arm fails due to an assembler error:

```
/tmp/cc1xIMEi.s: Assembler messages:
/tmp/cc1xIMEi.s:249: Error: operand 1 must be an integer register -- `rev16 r2,x0'
/tmp/cc1xIMEi.s:250: Error: operand 1 must be an integer register -- `strh r2,[x3]'
/tmp/cc1xIMEi.s:276: Error: operand 1 must be an integer register -- `rev r2,x0'
/tmp/cc1xIMEi.s:277: Error: operand 1 must be an integer register -- `str r2,[x3]'
make[6]: *** [Makefile:306: src/autoconf.o] Error 1
make[6]: *** Waiting for unfinished jobs....
```

**Comment by garbear** [comment]
Release tags have been created. I just tagged a new version for translation updates:

https://github.com/kodi-game/game.libretro.uae4arm/compare/0.5.0.5-Nexus...0.5.0.6-Nexus

I'll send a PR to LE.
